# Generated by Django 4.1.3 on 2022-11-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='feat_artist',
            field=models.ManyToManyField(blank=True, related_name='Feat', to='API.artist'),
        ),
    ]
