# Generated by Django 4.1.3 on 2022-11-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_song_feat_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.CreateModel(
            name='PlaylistOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_num', models.SmallIntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.song')),
            ],
        ),
    ]
