# Generated by Django 4.1.3 on 2022-11-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_playlist_songs_playlistorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='API.PlaylistOrder', to='API.song'),
        ),
    ]
