# Generated by Django 4.1.3 on 2022-11-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_artist_song_main_artist_song_feat_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='feat_artist',
            field=models.ManyToManyField(related_name='Feat', to='API.artist'),
        ),
    ]
